spring:
  application:
    name: instructions-capture-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.properties.case: false
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "com.example.instructions.model, com.example.instructions.model.*"

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.instructions.model"
        spring.json.value.default.type: "com.example.instructions.model.CanonicalTrade"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer